name: Deploy DEV

on:
  workflow_dispatch:

jobs:

  terraform:

    uses: ./.github/workflows/terraform-reusable.yml

    with:
      environment: dev
    #  terraform_version: "1.15.3"
      name: "prady"

    # secrets:
    #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}