# "workflow_call" makes a workflow reusable. 
# "workflow_call" work on JOB level not steps level
# Use "with" for inputs
# Use "secrets" for sensitive data like secrets
name: Reusable Terraform Workflow

on:
  workflow_call:

    inputs:
       name:
        required: true
        type: string  

       environment:
         description: "Terraform environment"
         required: true
         type: string



jobs:

   test-reusable-job:

    runs-on: ubuntu-latest

    steps:

      - name: Hello
        run: |
          echo "Hello ${{ inputs.name }}"
          echo "environment is ${{inputs.environment}}"
          echo "This message came from a reusable workflow."